version: '3.7'

services:
  PostgresDB:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    restart: unless-stopped

  PG_Admin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    restart: unless-stopped

  UserService:
    image: user-service
    ports:
      - "8080:8080"
    environment:
      - DB_HOSTNAME=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DBNAME=postgres
      - POSTGRES_USERNAME=admin
      - POSTGRES_PASS=admin
      - VERIFICATION_MAIL_USERNAME=eyadyoussef69@gmail.com
      - VERIFICATION_MAIL_PASSWORD=ifobbplpqanlsqjx