version: "3.3"

services:
  postgres:
    container_name: StudentGrades
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 38043
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    container_name: ExamsDatabase
    image: redis/redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redisdata:/var/lib/redis/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: RabbitMQ
    volumes:
      - rabbit-data:/data/rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  exam-service:
    container_name: ExamService
    image: eyadzz/dexam_exam_service:latest
    ports:
      - "8888:8888"
    environment:
      - EXAM_SERVER_PORT=:8888
      - DEVELOPMENT=true
      - REDIS_DB_HOST=redis
      - REDIS_DB_PORT=:6379
      - REDIS_DB_PASSWORD=
      - REDIS_DB_NAME=0#Default DB
      - PG_DB_HOST=postgres
      - PG_DB_PORT=5432
      - PG_DB_USER=postgres
      - PG_DB_PASSWORD=38043
      - PG_DB_NAME=postgres
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=:5672
    depends_on:
      - "postgres"
      - "redis"
      - "rabbitmq"
    links:
      - "postgres"
      - "redis"
      - "rabbitmq"
    restart: unless-stopped


volumes:
  redisdata:
  rabbit-data:
  pgdata: