version: '3.7'

services:
  postgres:
    image: postgres:14.4-alpine
    container_name: Postgres
    volumes:
      - db-data:/data/postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - PGDATA=/data/postgres
    restart: unless-stopped

  user-service:
    image: eyadzz/dexam_user_service
    container_name: UserService
    volumes:
      - user-service-data:/data/user_service
    ports:
      - "8080:8080"
    environment:
      - DB_HOSTNAME=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DBNAME=postgres
      - POSTGRES_USERNAME=admin
      - POSTGRES_PASS=admin
      - VERIFICATION_MAIL_USERNAME=eyadyoussef69@gmail.com
      - VERIFICATION_MAIL_PASSWORD=ifobbplpqanlsqjx
    restart: unless-stopped

volumes:
  db-data:
  user-service-data: