version: "3.7"

services:
  postgres:
    container_name: Postgres
    image: postgres:14.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 38043
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/data/postgresql
    restart: unless-stopped
  

  redis:
    container_name: Redis
    image: redis/redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redisdata:/data/redis
    restart: unless-stopped
  

  rabbitmq:
    build: .
    container_name: RabbitMQ
    ports:
    - 15672:15672
    - 5672:5672
    restart: unless-stopped
    volumes:
    - rabbit-data:/data/rabbit


  user-service:
    image: eyadzz/dexam_user_service:latest
    container_name: UserService
    volumes:
      - user-service-data:/data/user_service
    ports:
      - "8080:8080"
    environment:
      - DB_HOSTNAME=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DBNAME=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASS=38043
      - VERIFICATION_MAIL_USERNAME=eyadyoussef69@gmail.com
      - VERIFICATION_MAIL_PASSWORD=ifobbplpqanlsqjx
      - AUTH_SECRET_KEY=Thisismytestprivatekey
    restart: unless-stopped
    depends_on:
      - "postgres"
    links:
      - "postgres"

  
  course-service:
    image: eyadzz/dexam_course_service:latest
    container_name: CourseService
    volumes:
      - course-service-data:/data/course_service
    ports:
      - "443:443"
      - "80:80"
    environment:
      - REDIS_CONNECTION_STRING=redis://redis:6379
      - RABBITMQ_HOST_NAME=rabbitmq
    restart: unless-stopped
    depends_on:
      - "redis"
      - "rabbitmq"
    links:
      - "redis"
      - "rabbitmq"


  exam-service:
    container_name: ExamService
    image: eyadzz/dexam_exam_service:latest
    volumes:
      - exam-service-data:/data/exam_service
    ports:
      - "8888:8888"
    environment:
      - EXAM_SERVER_PORT=:8888
      - DEVELOPMENT=true
      - REDIS_DB_HOST=redis
      - REDIS_DB_PORT=:6379
      - REDIS_DB_PASSWORD=
      - REDIS_DB_NAME=0#Default DB
      - PG_DB_HOST=postgres
      - PG_DB_PORT=5432
      - PG_DB_USER=postgres
      - PG_DB_PASSWORD=38043
      - PG_DB_NAME=postgres
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=:5672
    depends_on:
      - "postgres"
      - "redis"
      - "rabbitmq"
    links:
      - "postgres"
      - "redis"
      - "rabbitmq"
    restart: unless-stopped

  
  api-gateway:
    image: eyadzz/dexam_api_gateway:latest
    container_name: APIGateway
    ports:
      - "5500:80"
    environment:
      - GATEWAY_JSON_FILE=Ocelot.json
      - AUTH_SECRET_KEY=Thisismytestprivatekey
    restart: unless-stopped

  
  overseer-service:
    container_name: OverseerService
    image: eyadzz/dexam_overseer_service:latest
    ports:
      - "9999:9999"
    environment:
      - OVERSEER_SERVER_PORT=:9999
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=:5672
    depends_on:
      - "rabbitmq"
    links:
      - "rabbitmq"
    restart: unless-stopped


volumes:
  redisdata:
  pgdata:
  rabbit-data:
  course-service-data:
  user-service-data:
  exam-service-data: