apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-deployment
  labels:
    app: dexam-course
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dexam-course
  template:
    metadata:
      labels:
        app: dexam-course
    spec:
      containers:
        - name: dexam-course
          image: eyadzz/dexam_course_service:latest
          ports:
            - containerPort: 80
          env:
            - name: REDIS_CONNECTION_STRING
              value: redis://redis-service:6379
            - name: RABBITMQ_HOST_NAME
              value: rabbitmq-service
---
apiVersion: v1
kind: Service
metadata:
  name: course-service
  annotations:
    konghq.com/plugins: jwt-auth
spec:
  selector:
    app: dexam-course
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80