apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-deployment
  labels:
    app: dexam-exam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dexam-exam
  template:
    metadata:
      labels:
        app: dexam-exam
    spec:
      containers:
        - name: dexam-exam
          image: eyadzz/dexam_exam_service:latest
          ports:
            - containerPort: 80
          env:
            - name: EXAM_SERVER_PORT
              value: :8888
            - name: DEVELOPMENT
              value: "true"
            - name: REDIS_DB_HOST
              value: redis-service
            - name: REDIS_DB_PORT
              value: :6379
            - name: REDIS_DB_NAME
              value: 0#Default DB
            - name: PG_DB_HOST
              value: postgres-service
            - name: PG_DB_PORT
              value: "5432"
            - name: PG_DB_USER
              valueFrom:
                secretKeyRef:
                  key: postgres-username
                  name: dexam-secret
            - name: PG_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres-password
                  name: dexam-secret
            - name: PG_DB_NAME
              value: postgres
            - name: RABBITMQ_HOST
              value: rabbitmq-service
            - name: RABBITMQ_PORT
              value: :5672
---
apiVersion: v1
kind: Service
metadata:
  name: exam-service
spec:
  selector:
    app: dexam-exam
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888