apiVersion: apps/v1
kind: Deployment
metadata:
  name: fr-deployment
  labels:
    app: dexam-fr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dexam-fr
  template:
    metadata:
      labels:
        app: dexam-fr
    spec:
      containers:
        - name: dexam-fr
          image: eyadzz/dexam_fr_service:latest
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: fr-service
spec:
  selector:
    app: dexam-fr
  ports:
    - port: 8001
      protocol: TCP
      targetPort: 8001