apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: jwt-auth
config: 
  secret_is_base64: false
  run_on_preflight: true
plugin: jwt

---

apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: admin
  annotations:
    kubernetes.io/ingress.class: kong
username: admin
credentials:
  - app-admin-jwt
---

apiVersion: v1
kind: Secret
metadata:
  name: app-admin-jwt
  namespace: default
stringData:
  algorithm: HS256
  key: dexam-issuer
  secret: Thisismytestprivatekey
  kongCredType: jwt
type: Opaque