apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-set
  labels:
    app: postgres
spec:
  replicas: 2
  serviceName: "postgres-service"
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: database-volume
              mountPath: /data/postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: postgres-username
                  name: dexam-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres-password
                  name: dexam-secret
      volumes:
        - name: database-volume
          persistentVolumeClaim:
            claimName: azure-files
            
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  port: 5432
  clusterIP: None