apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-set
  labels:
    app: redis
spec:
  replicas: 1
  serviceName: "redis-service"
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: redis
          image: redis/redis-stack
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: database-volume
              mountPath: /data/redis
      volumes:
        - name: database-volume
          persistentVolumeClaim:
            claimName: azure-files
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379