apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: dexam-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dexam-user
  template:
    metadata:
      labels:
        app: dexam-user
    spec:
      containers:
        - name: dexam-user
          image: eyadzz/dexam_user_service:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOSTNAME
              value: postgres-service
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DBNAME
              value: postgres
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  key: postgres-username
                  name: dexam-secret
            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  key: postgres-password
                  name: dexam-secret
            - name: VERIFICATION_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  key: email
                  name: dexam-secret
            - name: VERIFICATION_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: verification-email-password
                  name: dexam-secret
            - name: AUTH_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: auth_secret_key
                  name: dexam-secret

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: dexam-user
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30010