apiVersion: v1
kind: Secret
metadata:
  name: userservice-secret
type: Opaque
data:
  redis-database-password:
  redis-database-name: MA==
  postgres-database-password: MzgwNDM=
  postgres-database-name: MA==

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: examservice-deployment
  labels:
    app: exam-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exam-service
  template:
    metadata:
      labels:
        app: exam-service
    spec:
      containers:
        - name: exam-service
          image: eyadzz/dexam_exam_service
          ports:
            - containerPort: 8888
          env:
            - name: DEVELOPMENT
              value: "true"
            - name: REDIS_DB_HOST
              value: "redis"
            - name: REDIS_DB_PORT
              value: ":6379"
            - name: REDIS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-database-password
                  name: examservice-secret
            - name: REDIS_DB_NAME
              valueFrom:
                secretKeyRef:
                  key: redis-database-name
                  name: examservice-secret
            - name: PG_DB_HOST
                value: "postgres"
            - name: PG_DB_PORT
              value: "5432"
            - name: PG_DB_USER
                value: "postgres"
            - name: PG_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres-database-password
                  name: examservice-secret
            - name: PG_DB_NAME
              valueFrom:
                secretKeyRef:
                  key: postgres-database-name
                  name: examservice-secret
            - name: RABBITMQ_HOST
                value: "rabbitmq"
            - name: RABBITMQ_HOST
              value: ":5672"

---

apiVersion: v1
kind: Service
metadata:
  name: examservice-service
spec:
  selector:
    app: exam-service
  type: LoadBalancer
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
      nodePort: 30002