apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  selector:
    app: pgadmin
  type: NodePort
  ports:
    - port: 5050
      protocol: TCP
      targetPort: 80
      nodePort: 30000