name: Overseer-Service CI

on:
  push:
    branches: [ "Overseer-Service" ]
  pull_request:
    branches: [ "Overseer-Service" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: eyadzz/overseer_service
          registry: docker.io
          dockerfile: Dockerfile
          tags: latest
          addLatest: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
